#include "KaikkiImporter.h"

#include <algorithm>
#include <cctype>
#include <iostream>
#include <nlohmann/json.hpp>
#include <optional>
#include <sstream>
#include <string_view>
#include <vector>

#include "dct/dct.h"

/**
 * This is an JSONL importer that migrated from a python script to C++
 * This code was generated by AI, exuse any informal stylistic issues
 * It is strictly for importing the Kaikki web extract into the .db file
 */

namespace {

void execOrThrow(sqlite3 *db, const char *sql) {
  char *errMsg = nullptr;
  const int rc = sqlite3_exec(db, sql, nullptr, nullptr, &errMsg);
  if (rc != SQLITE_OK) {
    std::string msg = errMsg ? errMsg : "sqlite error";
    sqlite3_free(errMsg);
    throw std::runtime_error(msg);
  }
}

void begin(sqlite3 *db) { execOrThrow(db, "BEGIN;"); }

void commit(sqlite3 *db) { execOrThrow(db, "COMMIT;"); }

std::string trim(std::string_view in) {
  std::size_t start = 0;
  while (start < in.size() &&
         std::isspace(static_cast<unsigned char>(in[start]))) {
    ++start;
  }
  std::size_t end = in.size();
  while (end > start && std::isspace(static_cast<unsigned char>(in[end - 1]))) {
    --end;
  }
  return std::string{in.substr(start, end - start)};
}

std::string joinStrings(const nlohmann::json &arr) {
  if (!arr.is_array()) {
    return {};
  }
  std::string out;
  bool first = true;
  for (const auto &item : arr) {
    if (!item.is_string()) {
      continue;
    }
    const std::string s = trim(item.get<std::string_view>());
    if (s.empty()) {
      continue;
    }
    if (!first) {
      out.push_back(' ');
    }
    out += s;
    first = false;
  }
  return out;
}

std::string definitionFromSense(const nlohmann::json &sense) {
  if (!sense.is_object()) {
    return {};
  }
  if (sense.contains("glosses")) {
    const std::string joined = joinStrings(sense.at("glosses"));
    if (!joined.empty()) {
      return joined;
    }
  }
  if (sense.contains("raw_glosses")) {
    const std::string joined = joinStrings(sense.at("raw_glosses"));
    if (!joined.empty()) {
      return joined;
    }
  }
  if (sense.contains("gloss") && sense.at("gloss").is_string()) {
    return trim(sense.at("gloss").get<std::string_view>());
  }
  if (sense.contains("definition") && sense.at("definition").is_string()) {
    return trim(sense.at("definition").get<std::string_view>());
  }
  return {};
}

std::vector<std::string> extractTextList(const nlohmann::json &items,
                                         std::string_view key) {
  std::vector<std::string> out;
  if (!items.is_array()) {
    return out;
  }
  for (const auto &item : items) {
    std::string value;
    if (item.is_string()) {
      value = trim(item.get<std::string_view>());
    } else if (item.is_object()) {
      if (item.contains(key) && item.at(key).is_string()) {
        value = trim(item.at(key).get<std::string_view>());
      }
      if (value.empty() && key == "word") {
        if (item.contains("sense") && item.at("sense").is_string()) {
          value = trim(item.at("sense").get<std::string_view>());
        } else if (item.contains("translation") &&
                   item.at("translation").is_string()) {
          value = trim(item.at("translation").get<std::string_view>());
        }
      }
    }
    if (!value.empty()) {
      out.push_back(std::move(value));
    }
  }
  return out;
}

struct Stmt {
  sqlite3_stmt *stmt{nullptr};

  Stmt() = default;

  Stmt(sqlite3 *db, const char *sql) {
    if (sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr) != SQLITE_OK) {
      throw std::runtime_error("sqlite prepare failed");
    }
  }

  Stmt(const Stmt &) = delete;

  Stmt &operator=(const Stmt &) = delete;

  Stmt(Stmt &&other) noexcept : stmt(other.stmt) { other.stmt = nullptr; }

  Stmt &operator=(Stmt &&other) noexcept {
    if (this == &other) {
      return *this;
    }
    if (stmt) {
      sqlite3_finalize(stmt);
    }
    stmt = other.stmt;
    other.stmt = nullptr;
    return *this;
  }

  ~Stmt() {
    if (stmt) {
      sqlite3_finalize(stmt);
    }
  }

  void reset() const {
    sqlite3_reset(stmt);
    sqlite3_clear_bindings(stmt);
  }
};

std::optional<int> insertOrGetWordId(sqlite3 *db, Stmt &insertWord,
                                     Stmt &selectWord, std::string_view lemma,
                                     std::string_view displayLemma,
                                     int frequency, bool &inserted) {
  insertWord.reset();
  sqlite3_bind_text(insertWord.stmt, 1, lemma.data(),
                    static_cast<int>(lemma.size()), SQLITE_TRANSIENT);
  sqlite3_bind_text(insertWord.stmt, 2, displayLemma.data(),
                    static_cast<int>(displayLemma.size()), SQLITE_TRANSIENT);
  sqlite3_bind_int(insertWord.stmt, 3, frequency);

  if (sqlite3_step(insertWord.stmt) != SQLITE_DONE) {
    return std::nullopt;
  }
  inserted = (sqlite3_changes(db) > 0);

  selectWord.reset();
  sqlite3_bind_text(selectWord.stmt, 1, lemma.data(),
                    static_cast<int>(lemma.size()), SQLITE_TRANSIENT);
  if (sqlite3_step(selectWord.stmt) != SQLITE_ROW) {
    return std::nullopt;
  }
  return sqlite3_column_int(selectWord.stmt, 0);
}

} // namespace

KaikkiImportStats importKaikkiJsonl(Database &db, std::istream &jsonl,
                                    const KaikkiImportOptions &options) {
  KaikkiImportStats stats;

  db.createTables();
  if (options.clearDatabase) {
    db.clearDB();
  }

  sqlite3 *sqlDB = db.handle();
  if (!sqlDB) {
    throw std::runtime_error("database handle is null");
  }

  if (options.setFastPragmas) {
    execOrThrow(sqlDB, "PRAGMA journal_mode = WAL;");
    execOrThrow(sqlDB, "PRAGMA synchronous = OFF;");
    execOrThrow(sqlDB, "PRAGMA foreign_keys = ON;");
  }

  Stmt insertWord{sqlDB, "INSERT OR IGNORE INTO words (lemma, display_lemma, "
                         "frequency) VALUES (?, ?, ?);"};
  Stmt selectWord{sqlDB, "SELECT id FROM words WHERE lemma = ?;"};
  Stmt insertEtymology{
      sqlDB, "INSERT INTO etymologies (word_id, etymology) VALUES (?, ?);"};
  Stmt insertForm{sqlDB,
                  "INSERT INTO forms (word_id, form, tag) VALUES (?, ?, ?);"};
  Stmt insertSense{sqlDB, "INSERT INTO senses (word_id, pos, definition) "
                          "VALUES (?, ?, ?);"};
  Stmt insertExample{sqlDB,
                     "INSERT INTO examples (sense_id, example) VALUES (?, ?);"};
  Stmt insertSynonym{sqlDB,
                     "INSERT INTO synonyms (sense_id, synonym) VALUES (?, ?);"};
  Stmt insertAntonym{sqlDB,
                     "INSERT INTO antonyms (sense_id, antonym) VALUES (?, ?);"};

  begin(sqlDB);
  std::size_t pending = 0;

  std::string line;
  std::size_t lineNumber = 0;
  while (std::getline(jsonl, line)) {
    ++lineNumber;
    if (options.maxEntries != 0 && stats.entries >= options.maxEntries) {
      break;
    }

    const auto entry = nlohmann::json::parse(line, nullptr, false);
    if (entry.is_discarded() || !entry.is_object()) {
      continue;
    }

    if (entry.contains("lang_code")) {
      const auto &lang = entry.at("lang_code");
      if (lang.is_string() && lang.get<std::string_view>() != "en") {
        continue;
      }
    }

    std::string_view rawWord;
    if (entry.contains("word") && entry.at("word").is_string()) {
      rawWord = entry.at("word").get_ref<const std::string &>();
    } else {
      continue;
    }

    int frequency = 0;
    if (entry.contains("freq") && entry.at("freq").is_number_integer()) {
      frequency = entry.at("freq").get<int>();
    }

    const std::string lemma = dct::sanitizeWord(rawWord);
    if (lemma.empty()) {
      continue;
    }

    bool inserted = false;
    const auto maybeWordId = insertOrGetWordId(
        sqlDB, insertWord, selectWord, lemma, rawWord, frequency, inserted);
    if (!maybeWordId) {
      continue;
    }

    stats.entries += 1;
    if (inserted) {
      stats.words += 1;
    }

    const int wordId = *maybeWordId;

    if (entry.contains("etymology_text") &&
        entry.at("etymology_text").is_string()) {
      std::string_view ety =
          entry.at("etymology_text").get_ref<const std::string &>();
      std::stringstream ss(std::string{ety});
      std::string etyLine;
      while (std::getline(ss, etyLine)) {
        const std::string cleaned = trim(etyLine);
        if (cleaned.empty()) {
          continue;
        }
        insertEtymology.reset();
        sqlite3_bind_int(insertEtymology.stmt, 1, wordId);
        sqlite3_bind_text(insertEtymology.stmt, 2, cleaned.c_str(), -1,
                          SQLITE_TRANSIENT);
        if (sqlite3_step(insertEtymology.stmt) == SQLITE_DONE) {
          stats.etymologies += 1;
        }
      }
    }

    if (entry.contains("forms") && entry.at("forms").is_array()) {
      for (const auto &formEntry : entry.at("forms")) {
        if (!formEntry.is_object()) {
          continue;
        }
        if (!formEntry.contains("form") || !formEntry.at("form").is_string()) {
          continue;
        }
        const std::string form =
            dct::sanitizeWord(formEntry.at("form").get<std::string_view>());
        if (form.empty()) {
          continue;
        }

        std::string tag;
        if (formEntry.contains("tags") && formEntry.at("tags").is_array() &&
            !formEntry.at("tags").empty()) {
          const auto &first = formEntry.at("tags").front();
          if (first.is_string()) {
            tag = first.get<std::string>();
          }
        }

        insertForm.reset();
        sqlite3_bind_int(insertForm.stmt, 1, wordId);
        sqlite3_bind_text(insertForm.stmt, 2, form.c_str(), -1,
                          SQLITE_TRANSIENT);
        sqlite3_bind_text(insertForm.stmt, 3, tag.c_str(), -1,
                          SQLITE_TRANSIENT);
        if (sqlite3_step(insertForm.stmt) == SQLITE_DONE) {
          stats.forms += 1;
        }
      }
    }

    std::string entryPos;
    if (entry.contains("pos") && entry.at("pos").is_string()) {
      entryPos = trim(entry.at("pos").get<std::string_view>());
    }

    if (entry.contains("senses") && entry.at("senses").is_array()) {
      for (const auto &sense : entry.at("senses")) {
        const std::string definition = definitionFromSense(sense);
        if (definition.empty()) {
          continue;
        }

        std::string pos = entryPos;
        if (sense.is_object() && sense.contains("pos") &&
            sense.at("pos").is_string()) {
          const std::string sensePos =
              trim(sense.at("pos").get<std::string_view>());
          if (!sensePos.empty()) {
            pos = sensePos;
          }
        }

        insertSense.reset();
        sqlite3_bind_int(insertSense.stmt, 1, wordId);
        sqlite3_bind_text(insertSense.stmt, 2, pos.c_str(), -1,
                          SQLITE_TRANSIENT);
        sqlite3_bind_text(insertSense.stmt, 3, definition.c_str(), -1,
                          SQLITE_TRANSIENT);
        if (sqlite3_step(insertSense.stmt) != SQLITE_DONE) {
          continue;
        }

        const int senseId = static_cast<int>(sqlite3_last_insert_rowid(sqlDB));
        stats.senses += 1;

        if (sense.is_object() && sense.contains("examples")) {
          const auto examples = extractTextList(sense.at("examples"), "text");
          for (const auto &ex : examples) {
            insertExample.reset();
            sqlite3_bind_int(insertExample.stmt, 1, senseId);
            sqlite3_bind_text(insertExample.stmt, 2, ex.c_str(), -1,
                              SQLITE_TRANSIENT);
            if (sqlite3_step(insertExample.stmt) == SQLITE_DONE) {
              stats.examples += 1;
            }
          }
        }

        if (sense.is_object() && sense.contains("synonyms")) {
          const auto synonyms = extractTextList(sense.at("synonyms"), "word");
          for (const auto &syn : synonyms) {
            insertSynonym.reset();
            sqlite3_bind_int(insertSynonym.stmt, 1, senseId);
            sqlite3_bind_text(insertSynonym.stmt, 2, syn.c_str(), -1,
                              SQLITE_TRANSIENT);
            if (sqlite3_step(insertSynonym.stmt) == SQLITE_DONE) {
              stats.synonyms += 1;
            }
          }
        }

        if (sense.is_object() && sense.contains("antonyms")) {
          const auto antonyms = extractTextList(sense.at("antonyms"), "word");
          for (const auto &ant : antonyms) {
            insertAntonym.reset();
            sqlite3_bind_int(insertAntonym.stmt, 1, senseId);
            sqlite3_bind_text(insertAntonym.stmt, 2, ant.c_str(), -1,
                              SQLITE_TRANSIENT);
            if (sqlite3_step(insertAntonym.stmt) == SQLITE_DONE) {
              stats.antonyms += 1;
            }
          }
        }
      }
    }

    pending += 1;
    if (options.batchSize != 0 && pending >= options.batchSize) {
      commit(sqlDB);
      begin(sqlDB);
      pending = 0;
    }

    if (options.progressInterval != 0 &&
        stats.entries % options.progressInterval == 0) {
      std::cerr << "Processed " << stats.entries << " entries | " << stats.words
                << " unique lemmas | " << stats.senses << " senses\n";
    }
  }

  commit(sqlDB);
  return stats;
}
